// @/lib/panw-parser/device/index.ts

export type {
  SetupManagement,
  LogQuotaEntry,
  LogQuotaSet,
  GeneralSettings,
  AuthenticationSettings,
  LogInterface,
  PanoramaSettings,
  SecureCommunicationClient,
  SecureCommunicationServer,
  SecureCommunicationSettings,
  MultiDiskStorage,
  LogAdminActivity,
  LogExportAndReporting,
  PreDefinedReports,
  LoggingAndReportingSettings,
  AutoFocusSettings,
  CloudLoggingSettings,
  AccountingServerSettings,
  SshManagementProfileSetting,
  AdvancedDnsSecurity,
  PanOsEdgeServiceSettings,
  MessageOfTheDay,
  Banners,
  BannersAndMessages,
  PasswordFormatRequirements,
  PasswordFunctionalityRequirements,
  MinimumPasswordComplexity,
} from './setup'
